const fs = require('fs');
const path = require('path');

// Mock window object globally so that code expecting it runs seamlessly in Node.js
global.window = global;

// Read and evaluate calculator.js to load calculation functions globally
const calculatorCode = fs.readFileSync(path.join(__dirname, 'founder_tool_suite', 'calculator.js'), 'utf-8');
eval(calculatorCode);

// Read and evaluate docs_data.js to load FOUNDER_TOOLS templates globally
const docsDataCode = fs.readFileSync(path.join(__dirname, 'founder_tool_suite', 'docs_data.js'), 'utf-8');
eval(docsDataCode);

let compiledMarkdown = `# NEURONEDGE LABS INC. — FULL INCORPORATION & CORPORATE SETUP DRAFTS
### Built by **RJ Business Solutions** for **NeuronEdge Labs Inc.** | Architected by **Rick Jefferson**
📍 1342 NM 333, Tijeras, New Mexico 87059 | 🌐 [rickjeffersonsolutions.com](https://rickjeffersonsolutions.com)

---

> [!NOTE]
> This document compiles the full set of 18 legal, financial, and operational templates, agreements, and models generated by the **Startup Founder Tool Suite** for the Wyoming incorporation of **NeuronEdge Labs Inc.**

## Table of Contents
${FOUNDER_TOOLS.map((t, idx) => `${idx + 1}. [${t.name}](#${t.id})`).join('\n')}

---
`;

FOUNDER_TOOLS.forEach((tool) => {
  // Extract default values for all parameters
  const defaults = {};
  tool.fields.forEach((f) => {
    defaults[f.id] = f.default;
  });

  // Generate document text using the tool's template function
  const docMarkdown = tool.generator(defaults);

  compiledMarkdown += `\n<a id="${tool.id}"></a>\n\n## ${tool.name}\n\n${docMarkdown}\n\n---\n`;
});

// Ensure docs directory exists
const docsDir = path.join(__dirname, 'docs');
if (!fs.existsSync(docsDir)) {
  fs.mkdirSync(docsDir, { recursive: true });
}

// Write the output file
fs.writeFileSync(path.join(docsDir, 'NEURONEDGE_LABS_CORPORATE_DRAFTS.md'), compiledMarkdown, 'utf-8');
console.log('Successfully compiled all 18 documents to docs/NEURONEDGE_LABS_CORPORATE_DRAFTS.md');
