blank_issues_enabled: false
contact_links:
  - name: Support Request
    url: https://rickjeffersonsolutions.com
    about: For corporate or SLA technical support, please contact RJ Business Solutions directly.
